- hosts: localhost
  connection: local
  become: true
  roles:
    # - ./roles/core
    # - ./roles/dotfiles
    # - ./roles/starship
    # - ./roles/rust
    # - ./roles/neovim
    # - ./roles/lf
    # - ./roles/lua
    # - ./roles/golang
    # - ./roles/node
    # - ./roles/deno
    # GUI
    # - ./roles/sway
    # - ./roles/sway-fonts
    # - ./roles/ripdrag
    # - ./roles/satty
    # - ./roles/swww
    # - ./roles/chromium
    # - ./roles/pico
    # - ./roles/wooz
